### ISSUE TITLE
Personality

### ISSUE THREAD

**Issue by tommygebru** [Shealav/Capstone-Colmar#3]
As this is your last project, many students take this opportunity to add personal flair and really use their own design choices, like css transitions, hover actions, css gradients and a lot more!

Nice work on your typography Shealav, I like the use of bold uppercase letters as the logo typeface, the headings and textual elements are large and legible as well 👍 

One suggestion would be to include more mouse interactions, I like to quickly add these to my projects with `cursor: pointer` and apply them to links and buttons in my CSS

**Comment by tommygebru** [comment]
I also wanted to share that there are some excellent resources out there to help with creating a color palette as well https://mymodernmet.com/color-palette-generator/

Also there are a few typography resources I think will be helpful
https://fontjoy.com/ uses AI to help pair fonts
https://fontcdn.org/ a great tool to try out fonts quickly

**Comment by Shealav** [comment]
Wonderful ideas! Thank you.
