### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by tommygebru** [Shealav/Capstone-Colmar#4]
Really nice work on using multiple images for separate layouts Shealav,
also really great use of fluid typography and responsive web design made possible with REM
[Implementing REM in CSS (or, How to Be a Shiny Happy Developer) - Words and Code](https://vaidehijoshi.github.io/blog/2015/01/20/implementing-rem-in-css-or-how-to-be-a-shiny-happy-developer/)

Your transition between different layouts is smooth, great use of the entire pages length and width. 👍

**Comment by tommygebru** [comment]
**Minor typos and errors:**

- Consider applying a `height` to your courses card elements, as well as your images!

**Comment by Shealav** [comment]
I wondered how to make those the size that I wanted. Duh! ;)
